yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(
        template_name='about/author.html'), name='author'),
    path('tech/', views.AboutTechView.as_view(
        template_name='about/tech.html'), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Имя группы"
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="Адрес Slug"
    )
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name="Содержание статьи",
        help_text="Введите текст статьи",
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации статьи"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор",
        help_text="Введите автора статьи"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name="Группа"
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:30]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    text = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.text, self.post)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='one_love'
            ),
            models.CheckConstraint(
                name='authoe_author',
                check=~models.Q(user=models.F('author'))
            )
        ]

    def __str__(self):
        return f'Подписчик {self.user}, Автор {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm, Select, Textarea

from posts.models import Comment, Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        labels = {
            'text': 'Текст поста',
            'group': 'Group'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа к которой относится пост',
        }
        fields = ['text', 'group', 'image']
        widgets = {
            'text': Textarea(attrs={
                'name': 'text',
                'cols': '40',
                'rows': '10',
                'class': 'form-control',
                'id': 'id_text'
            }),
            'group': Select(attrs={
                'name': 'group',
                'class': 'form-control',
                'id': 'id_group'
            }),
        }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={
                'name': 'text',
                'cols': '40',
                'rows': '10',
                'class': 'form-control',
                'id': 'id_text'
            })
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

import utils
from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User


def index(request):
    template = 'posts/index.html'
    context = utils.get_page_context(Post.objects.all(), request)
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(utils.get_page_context(group.posts.all(), request))
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    profile_posts = author.posts.all()
    profile_count = profile_posts.count()
    user = request.user
    following = None
    if user.is_authenticated:
        following = Follow.objects.filter(
            user=user, author=author
        ).exists()
    context = {
        'profile_count': profile_count,
        'author': author,
        'following': following
    }
    context.update(utils.get_page_context(author.posts.all(), request))
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_count = author.posts.all().count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    error = ''
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        form = form.save(False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', form.author.username)
    else:
        error = 'Данные не корректны'
    context = {
        'form': form,
        'error': error
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    context = {
        'post_list': post_list,
    }
    context.update(utils.get_page_context(post_list, request))
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if (request.user != author and not Follow.objects.filter
            (user=request.user, author=author).exists()):
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if not post %} Новый пост {% else %} Редактировать пост {% endif %}{% endblock %}
{% block content %}
<div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">{% if not post %} Новый пост {% else %} Редактировать пост {% endif %}</div>
              <div class="card-body">
              {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}        
              <form method="post" enctype="multipart/form-data" action={% if post %}"{% url 'posts:post_edit' post_id=post.id %}"{% else %}"{% url 'posts:post_create' %}"{% endif %}>
              {% csrf_token %}            
                <div class="form-group row my-3 p-3">
                  <p>{{ form.text.label }}<span class="required text-danger">*</span></p>   
                    {{ form.text }}            
                    {{ form.text.help_text|safe }}                
                  </div>            
                  <div class="form-group row my-3 p-3">
                    {{ form.group.label }} 
                    {{ form.group }}
                    {{ form.group.help_text|safe }} 
                  </div>
                  <div>
                    {{ form.image.label }} 
                    {{ form.image }}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                             {% if is_edit %}
                             Сохранить
                             {% else %}
                             Добавить
                             {% endif %}               
                             </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}МОЯ ПРЕЛЕСТЬ{% endblock %}
{% block content %}
      <div class="container py-5"> 
        {% include 'posts/includes/switcher.html' %}    
        <h1>{{ text }}</h1>
        <article>
          {% for post in page_obj  %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
              <div>
              {% thumbnail post.image "320x160" crop="center" upscale=True as im %}
              <img style="margin:{{ im|margin:"100x700" }} class="card-img my-2" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"">
              {% endthumbnail %}
              <p>{{ post }}</p> 
              </div>
            {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы: {{ post.group.title }}</a
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>  
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <div>
              {% thumbnail post.image "320x160" crop="center" upscale=True as im %}
              <img style="margin:{{ im|margin:"100x700" }} class="card-img my-2" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"">
              {% endthumbnail %}
              <p>{{ post.text }}</p> 
              </div>
            {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы: {{ post.group.title }}</a
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>  
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
      <div class="container py-5"> 
        {% include 'posts/includes/switcher.html' %}    
        <h1>{{ text }}</h1>
        <article>
          {% cache 20 index_page %}
          {% for post in page_obj  %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все записи пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
              <div>
              {% thumbnail post.image "320x160" crop="center" upscale=True as im %}
              <img style="margin:{{ im|margin:"100x700" }} class="card-img my-2" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"">
              {% endthumbnail %}
              <p>{{ post }}</p> 
              </div>
              <div>
                <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
              </div>
            {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы: {{ post.group.title }}</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% endcache %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>  
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ post.text|slice:30 }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>               
        <li class="list-group-item">
          Группа: {{ post.group }}
          {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы: {{ post.group.title }}</a
            {% endif %}
        </li>            
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
          {% if request.user.username == post.author.username %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %} 
  </article>
      </div>  
      
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Проффайл пользователя {{ author }} {% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>Все посты пользователя: {{ author }}</h1>
        <p>
          Всего постов: {{ profile_count }}
        </p>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            {% if user.is_authenticated %}
              {% if request.user.username != post.author.username %}
              <li>
                {% if following %}
                <a
                 class="btn btn-lg btn-light"
                 href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                 Отписаться
                </a>
                {% else %}
                <a
                 class="btn btn-lg btn-primary"
                 href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                Подписаться
                </a>
                {% endif %}
              </li>
              {% endif %}
              {% endif %}
            </ul>
            <div>
              {% thumbnail post.image "320x160" crop="center" upscale=True as im %}
              <img style="margin:{{ im|margin:"100x700" }} class="card-img my-2" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}"">
              {% endthumbnail %}
              <p>{{ post.text }}</p> 
              </div>
            {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы: {{ post.group.title }}</a
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>  
{% endblock %} 